const Menu=[{
    id:1,
    image:"https://www.indianfoodforever.com/iffwd/wp-content/uploads/kadhi-chawal-1.jpg",
    name:"KADHI-CHAWAL",
    category:"dinner",
    price:"60/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:2,
    image:"https://t4.ftcdn.net/jpg/03/91/22/09/360_F_391220948_voYb3Unzpl4sRu40CPFSNRAbCgMOJze5.jpg",
    name:"RAJAMA-CHAWAL",
    category:"lunch",
    price:"50/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem!.",   
},
{
    id:3,
    image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP1BPNz-B2gQ74d1k2-1bGmdRxilS-JXQShJpF-f3DGZAwZgh2QEBcRvG7KXuSGV9Pr_I&usqp=CAU",
    name:"CHILLI-PATATO",
    category:"evening",
    price:"60/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:4,
    image:"https://media.istockphoto.com/id/1292635321/photo/veg-steam-momo-nepalese-traditional-dish-momo-stuffed-with-vegetables-and-then-cooked-and.jpg?s=612x612&w=0&k=20&c=NyxQvDnBq7Ki09Zi21JEMxpuZ_uVr45ZBSavqXJ2T1s=",
    name:"MOMOSE",
    category:"evening",
    price:"60/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:5,
    image:"https://thumbs.dreamstime.com/b/indian-breakfast-aloo-paratha-potato-pancakes-served-yogurt-dip-87658775.jpg",
    name:"ALU-PARATHA",
    category:"lunch",
    price:"60/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:6,
    image:"https://thumbs.dreamstime.com/b/close-up-shahi-paneer-cottage-cheese-curry-peppers-cooked-rich-tomato-sauce-classic-traditional-north-indian-158606596.jpg",
    name:"SAHI-PANEER",
    category:"dinner",
    price:"60/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:7,
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Punjabi_style_Dal_Makhani.jpg/640px-Punjabi_style_Dal_Makhani.jpg",
    name:"DAL-MAKHANI",
    category:"dinner",
    price:"70/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:8,
    image:"https://media.istockphoto.com/photos/punjabi-samosa23-picture-id502663991?k=20&m=502663991&s=612x612&w=0&h=jC4KxvXhgWxueNgtMJar4BYTcVN_NQH1k-qVMsJ_eCE=",
    name:"SAMOSA",
    category:"evening",
    price:"40/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:9,
    image:"https://thumbs.dreamstime.com/b/pizza-rustic-italian-mozzarella-cheese-basil-leaves-35669930.jpg",
    name:"PIZZA",
    category:"evening",
    price:"160/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:10,
    image:"https://static.toiimg.com/photo/76193045.cms",
    name:"MAGGI",
    category:"Breakfast",
    price:"160/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:11,
    image:"https://media.istockphoto.com/id/628964312/photo/indian-masala-chai-tea-spiced-tea-with-milk.jpg?s=612x612&w=0&k=20&c=myE8bvu3vmUYx1hecbmOa1zzpFI0Mgw9DlN4Bl0bsms=",
    name:"MASALA-CHAI",
    category:"Breakfast",
    price:"160/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:12,
    image:"https://media.istockphoto.com/id/1292640499/photo/bread-pakora-or-pakoda-served-with-chutney-a-famous-midday-snack-in-india-served-in-white.jpg?s=612x612&w=0&k=20&c=GqMce-o6TTohjd4HvhUoAtrB16X2svWT9srQ02SgQYc=",
    name:"BREAD-PAKORA",
    category:"Breakfast",
    price:"160/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:13,
    image:"https://thumbs.dreamstime.com/b/close-up-shahi-paneer-cottage-cheese-curry-peppers-cooked-rich-tomato-sauce-classic-traditional-north-indian-158606596.jpg",
    name:"SAHI-PANEER",
    category:"lunch",
    price:"60/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:14,
    image:"https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Punjabi_style_Dal_Makhani.jpg/640px-Punjabi_style_Dal_Makhani.jpg",
    name:"DAL-MAKHANI",
    category:"lunch",
    price:"70/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:15,
    image:"https://media.istockphoto.com/id/1292640499/photo/bread-pakora-or-pakoda-served-with-chutney-a-famous-midday-snack-in-india-served-in-white.jpg?s=612x612&w=0&k=20&c=GqMce-o6TTohjd4HvhUoAtrB16X2svWT9srQ02SgQYc=",
    name:"BREAD-PAKORA",
    category:"evening",
    price:"160/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
{
    id:16,
    image:"https://t4.ftcdn.net/jpg/03/91/22/09/360_F_391220948_voYb3Unzpl4sRu40CPFSNRAbCgMOJze5.jpg",
    name:"RAJAMA-CHAWAL",
    category:"dinner",
    price:"50/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem!.",   
},
{
    id:5,
    image:"https://thumbs.dreamstime.com/b/indian-breakfast-aloo-paratha-potato-pancakes-served-yogurt-dip-87658775.jpg",
    name:"ALU-PARATHA",
    category:"dinner",
    price:"60/only-",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, dolorem! .",   
},
]
export default Menu;